#!/bin/bash
set -e

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
NVIM_CONFIG_DIR="$HOME/.config/nvim"
"$SCRIPT_DIR"/../../bin/pkg-install nvim --package neovim
"$SCRIPT_DIR"/../../bin/pkg-install nodejs
"$SCRIPT_DIR"/../../bin/pkg-install npm
if ! 2>/dev/null 1>&2 npm list -g tree-sitter-cli; then
    sudo npm install -g tree-sitter-cli # for LaTeX support
fi

echo "Setting up nvim-kickstart.."
if [[ ! -d "$NVIM_CONFIG_DIR" ]]; then
    mkdir -p "$NVIM_CONFIG_DIR" && cd "$NVIM_CONFIG_DIR"
    git clone https://github.com/nvim-lua/kickstart.nvim.git .
else
    if "$SCRIPT_DIR/../../bin/prompt-yn" "Do you want to git reset --hard $NVIM_CONFIG_DIR?"; then
        cd "$NVIM_CONFIG_DIR"
        git reset --hard
    else
        echo ":$0 error: Can't put configs over existing configs. Exiting.."
        exit 0
    fi
fi

echo "Patching nvim-kickstart.."
# patch created with git diff >filename.patch
git apply "$SCRIPT_DIR"/nvim-kickstart-patch.diff
echo "nvim-kickstart setup complete."

