#!/bin/bash
set -e


PACMAN=
APT_GET=


LONGOPTS=pacman:,apt-get:


PARSED=$(getopt --options='' --longoptions=$LONGOPTS --name "$0" -- "$@") || exit 1
eval set -- "$PARSED"

while true; do
  case "$1" in
    --pacman)
      PACMAN="$2"
      shift 2
      ;;
    --apt-get)
      APT_GET="$2"
      shift 2
      ;;
    --)
      shift
      break # -- signals end of optional arguments
      ;;
    *)
      echo "wow, something went wrong"
      exit 1
      ;;
  esac
done

#echo "PACMAN:$PACMAN"
#echo "APT_GET:$APT_GET"


if [[ ! -z $(which pacman) ]]; then
  sudo pacman -Sy "$PACMAN"
elif [[ ! -z $(which apt-get) ]]; then
  sudo apt-get -Sy "$APT_GET"
else
  echo "Package manager not supported or not found and installing from source is not yet supported."
  exit 1
fi

