#!/bin/bash

# TODO: fix wildcard wildcard * on install

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
SYNC_MODE=$1
REPO_DIR=$SCRIPT_DIR
SF="$SCRIPT_DIR/../bin/syncfiles $@"


echo "Copying shell configs"
$SF ~ .bashrc
$SF ~ .bash_aliases
$SF ~ .zshrc
$SF ~ .p10k.zsh
$SF ~ .env
$SF ~ .env_laptop
$SF ~ .env_vm

echo "Copying X11 configs"
$SF ~ .xsession
$SF -t . ~ .Xresources*

echo "Copying GTK configs"
$SF ~ .gtkrc-2.0
$SF ~ .config/gtk-3.0/settings.ini
$SF ~ .config/xsettingsd/xsettingsd.conf
$SF ~ .icons/default/index.theme
sudo $SF / usr/share/icons/default/index.theme
sudo $SF / etc/lightdm/slick-greeter.conf
sudo $SF / etc/xprofile

echo "Copying picom config"
$SF ~ .config/picom/.

echo "Copying xfce4 configs"
$SF ~ .config/xfce4/xfconf/xfce-perchannel-xml/xfce4-terminal.xml

echo "Copying .fehbg"
$SF ~ .fehbg

echo "Copying i3 config"
I3_CONFIG=".config/i3"
$SF ~ $I3_CONFIG/{config,workspaces.conf,i3blocks.conf}
$SF -t $I3_CONFIG/ ~ $I3_CONFIG/theme*.conf
$SF ~ $I3_CONFIG/scripts/.

echo "Copying remontoire config"
$SF ~ .config/remontoire/.

echo "Copying polybar config"
$SF ~ .config/polybar/.


echo "Copying uwsm config"
$SF ~ .config/uwsm/.

echo "Copying hyprland config"
HYPR_CONFIG=".config/hypr"
$SF ~ $HYPR_CONFIG/.

echo "Copying waybar config"
$SF ~ .config/waybar/.

echo "Copying hyprpanel config"
$SF ~ .config/hyprpanel/.

echo "Copying wlogout config"
$SF ~ .config/wlogout/.

echo "Copying wofi config"
$SF ~ .config/wofi/.

echo "Copying tofi config"
$SF ~ .config/tofi/.

echo "Copying foot config"
$SF ~ .config/foot/.


echo "Copying dunst config"
$SF ~ .config/dunst/.

echo "Copying libinput gestures"
$SF ~ .config/libinput-gestures.conf

echo "Copying mimeapps.list"
$SF ~ .config/mimeapps.list

echo "Copying xfce4-terminal-run.desktop"
sudo $SF / usr/share/applications/xfce4-terminal-run.desktop

