#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
SOFTWARE_DIR="$SCRIPT_DIR"/../software
I3_CONFIG=$HOME/.config/i3

cd $SCRIPT_DIR
$SCRIPT_DIR/syncfiles -e -r .

echo "Special copy of thunar.xml"
cat ~/.config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml | grep -E "xml|channel|hidden">$SCRIPT_DIR/.config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml

echo "Creating i3blocks-contrib diff"
cp $I3_CONFIG/i3blocks-contrib/.git/info/sparse-checkout $SCRIPT_DIR/i3blocks-contrib-checkout
cd $I3_CONFIG/i3blocks-contrib
git add -N $I3_CONFIG/i3blocks-contrib/arch-update/arch-update.sh
git add -N $I3_CONFIG/i3blocks-contrib/mediaplayer/mp-scrolling
git add -N $I3_CONFIG/i3blocks-contrib/mediaplayer/mp-switching
git diff >"${SCRIPT_DIR}/i3blocks-contrib-patch.diff"

"$SOFTWARE_DIR"/ranger/update
"$SOFTWARE_DIR"/rofi/update
"$SOFTWARE_DIR"/nvim/update
"$SOFTWARE_DIR"/zathura/update
"$SOFTWARE_DIR"/i3expo/update
"$SOFTWARE_DIR"/tmux/update

