#!/bin/bash
set -e


SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)


"$SCRIPT_DIR"/../bin/pkg_install nvim --pacman neovim

echo "Setting up nvim-kickstart.."
mkdir -p ~/.config/nvim && cd ~/.config/nvim
# NOTE: clear dir?
git clone https://github.com/nvim-lua/kickstart.nvim.git .
echo "Patching nvim-kickstart.."
# patch created with git diff >filename.patch
git apply "$SCRIPT_DIR"/nvim/nvim-kickstart-patch.diff
echo "nvim-kickstart setup complete."

