#!/bin/bash
set -e


SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
BIN_DIR="$SCRIPT_DIR/../bin"


# oh my zsh
if [ -d ~/.oh-my-zsh/ ]
then
  echo "oh-my-zsh exists, skipping.."
else
  echo "Setting up oh my zsh .."
  sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
fi

if [ -d ~/.oh-my-zsh/plugins/zsh-syntax-highlighting ]
then
  echo "zsh-syntax-highlight -plugin found, skipping.."
else
  echo "Installing zsh-syntax-highlighting .."
  cd ~/.oh-my-zsh/plugins/
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
  echo "zsh-syntax-highlighting installed."
fi

if [ -d ~/.oh-my-zsh/plugins/zsh-autosuggestions ]
then
  echo "zsh-autosuggestions -plugin found, skipping.."
else
  echo "Installing zsh-autosuggestions .."
  cd ~/.oh-my-zsh/plugins/
  git clone https://github.com/zsh-users/zsh-autosuggestions
  echo "zsh-autosuggestions installed."
fi

# p10k theme
if [ -f ~/.p10k.zsh ]
then
  echo "p10k config found, skipping"
else
  echo "Installing powerlevel10k theme for zsh.."
  yay -S --noconfirm zsh-theme-powerlevel10k-git
  echo "powerlevel10k setup complete."
fi
echo "Copying .p10k.zsh .."
cp "$SCRIPT_DIR/ohmyzsh/.p10k.zsh" ~/

