#!/bin/bash
set -e

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
RANGER_CONFIG_DIR="$HOME/.config/ranger"

"$SCRIPT_DIR"/../bin/pkg-install ranger
"$SCRIPT_DIR"/../bin/pkg-install w3m
"$SCRIPT_DIR"/../bin/pkg-install mpv
"$SCRIPT_DIR"/../bin/pkg-install highlight

if [[ -d "$RANGER_CONFIG_DIR" ]]; then
    if "$SCRIPT_DIR/../bin/prompt-yn" "Do you want to clear $RANGER_CONFIG_DIR?"; then
        rm -rf "$RANGER_CONFIG_DIR"
    else
        echo ":$0 error: Can't put configs over existing configs. Exiting.."
        exit 0
    fi
fi

mkdir -p "$RANGER_CONFIG_DIR"
cp -r "$SCRIPT_DIR/ranger/"* "$RANGER_CONFIG_DIR"
