#!/bin/bash
set -e


SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

"$SCRIPT_DIR"/../bin/pkg_install ranger
mkdir -p ~/.config/ranger
cp "$SCRIPT_DIR"/ranger/rc.conf ~/.config/ranger/
