#!/bin/bash
set -e

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
ROFI_THEME_DIR="$HOME/.local/share/rofi/themes"

mkdir -p "$ROFI_THEME_DIR" && cd "$ROFI_THEME_DIR"
echo "Copying theme simple-tokyonight-cuostm.rasi .."
cp "$SCRIPT_DIR/rofi/simple-tokyonight-custom.rasi" "$ROFI_THEME_DIR"

echo "Now apply the theme using rofi-theme-selector."
# NOTE: Possibly set ROFI theme automatically
# Change it in ~/.config/rofi/config.rasi

