#!/bin/bash
set -e

# NOTE: Installation size around 3 GiB

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

echo "Installing TeX Live .."
"$SCRIPT_DIR/../bin/pkg-install" pdflatex --package texlive # collection
"$SCRIPT_DIR/../bin/pkg-install" texlive-langeuropean
"$SCRIPT_DIR/../bin/pkg-install" biber
"$SCRIPT_DIR/../bin/pkg-install" texlive-langgreek
echo "TeX Live setup complete."

