#!/bin/bash
set -e

# NOTE: Installation size around 6GiB

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

echo "Installing TeX Live .."
"$SCRIPT_DIR/../bin/pkg_install" pdflatex --package texlive # collection
"$SCRIPT_DIR/../bin/pkg_install" biber

echo "TeX Live setup complete."

