#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
CONFIG_DIR=/etc/X11/xorg.conf.d

echo "copying xorg device configs .."
mkdir -p $SCRIPT_DIR/xorg
if [[ -f $CONFIG_DIR/90-touchpad.conf ]]; then
    cp $CONFIG_DIR/90-touchpad.conf $SCRIPT_DIR/xorg
fi
