#!/bin/bash
set -e

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
ROFI_CONFIG_DIR="$HOME/.config/rofi"

echo "Copying rofi theme and configs"
mkdir -p "$SCRIPT_DIR/configs"
cd "$ROFI_CONFIG_DIR"
cp -r . "$SCRIPT_DIR/configs"
