#!/bin/bash
set -e

# This installscript expects to have endeavour i3 installed.
# NOTE: Following changes are not automated:
# themes for xfce4-terminal and firefox, installation of additional eos background images

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
SOFTWARE="$SCRIPT_DIR/../software"
BIN_DIR="$SCRIPT_DIR/../bin"
CLEAN=false # Reserved for future use
DOWNLOAD_EOS_I3WM=false

# Parsing arguments src: https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash

LONGOPTS=clean,download-eos-i3wm

PARSED=$(getopt --options="" --longoptions=$LONGOPTS --name "$0" -- "$@") || exit 1
eval set -- "$PARSED"

while true; do
  case "$1" in
    --clean) CLEAN=true; shift ;;
    --download-eos-i3wm) DOWNLOAD_EOS_I3WM=true; shift ;;
    # -- signals end of optional arguments
    --) shift; break ;;
    *) echo "wow, something went wrong"; exit 1 ;;
  esac
done
#echo "CLEAN:$CLEAN"

# handle positional arguments
#echo "POSITIONAL_ARGUMENTS:$@"


echo "Installing prerequisites"
ensure_installed() {
  if ! command -v "$1" 2>&1 >/dev/null; then
    echo "$1" "not found, installing"
    shift
    for var in "$@"; do
      eval "$var"
    done
  fi
}

"$BIN_DIR/pkg-install" git
#"$BIN_DIR/pkg-install" zsh
ensure_installed yay \
  "sudo pacman -Sy --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si" \
  "cd .. && rm -rf yay" # cleanup

echo "Prerequisites are installed"


echo "Installing additional software"
"$BIN_DIR/pkg-install" libnewt # whiptail needed by uwsm
"$BIN_DIR/pkg-install" uwsm
"$BIN_DIR/pkg-install" hyprland
"$BIN_DIR/pkg-install" waybar
#"$BIN_DIR/pkg-install" rofimoji
#"$BIN_DIR/pkg-install" fuck --package thefuck # config is in .zshrc
#"$BIN_DIR/pkg-install" selectdefaultapplication-git
#"$BIN_DIR/pkg-install" downgrade
#"$BIN_DIR/pkg-install" rclone
#"$BIN_DIR/pkg-install" neofetch
#"$BIN_DIR/pkg-install" spotube-bin # music player
#"$BIN_DIR/pkg-install" xfce4-screenshooter
"$BIN_DIR/pkg-install" udiskie
"$BIN_DIR/pkg-install" gnome-system-monitor
#"$BIN_DIR/pkg-install" polybar
#"$BIN_DIR/pkg-install" orage

"$BIN_DIR/pkg-install" unclutter

# To get clipboard working
#"$BIN_DIR/pkg-install" xclip
#"$BIN_DIR/pkg-install" greenclip --aur rofi-greenclip

# Essential software
"$BIN_DIR/pkg-install" wofi
"$BIN_DIR/pkg-install" foot
"$BIN_DIR/pkg-install" thunar
"$BIN_DIR/pkg-install" firefox

"$SOFTWARE/nvim/install"
"$SOFTWARE/ranger/install"
#"$SOFTWARE/rofi/install"
#"$SOFTWARE/ohmyzsh/install"
"$SOFTWARE/zathura/install"
"$SOFTWARE/tmux/install"

#if "$BIN_DIR/prompt-yn" "Setup gestures?"; then
#  "$BIN_DIR/pkg-install" wmctrl
#  "$BIN_DIR/pkg-install" libinput-gestures --aur libinput-gestures
#  "$BIN_DIR/pkg-install" gestures --aur gestures
#  sudo usermod -a -G input jonir
#fi

echo "Installing themes, cursors and icons"
"$BIN_DIR/pkg-install" ttf-noto-nerd --exists /usr/share/fonts/TTF/NotoMonoNerdFont-Regular.ttf.ttf
"$BIN_DIR/pkg-install" ttf-font-awesome --exists /usr/share/fonts/TTF/fa-regular-400.ttf
echo "Themes installed."


cd $SCRIPT_DIR
$SCRIPT_DIR/syncfiles -i -r .

echo "DONE!"

