#!/bin/bash

# TODO: fix wildcard wildcard * on install

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
SYNC_MODE=$1
REPO_DIR=$SCRIPT_DIR
SF="$SCRIPT_DIR/../bin/syncfiles $@"

echo "Copying launch-gui"
$SF ~ .launch-gui

echo "Copying env config"
$SF ~ .env

echo "Copying shell configs"
$SF ~ .bashrc
$SF ~ .bash_aliases

#echo "Copying GTK configs"
#$SF ~ .gtkrc-2.0
#$SF ~ .config/gtk-3.0/settings.ini
#$SF ~ .icons/default/index.theme
#sudo $SF / usr/share/icons/default/index.theme
#sudo $SF / etc/lightdm/slick-greeter.conf

echo "Copying uwsm config"
$SF ~ .config/uwsm/.

echo "Copying hyprland config"
HYPR_CONFIG=".config/hypr"
$SF ~ $HYPR_CONFIG/.

echo "Copying waybar config"
$SF ~ .config/waybar/.


#echo "Copying mimeapps.list"
#$SF ~ .config/mimeapps.list

#echo "Copying xfce4-terminal-run.desktop"
#sudo $SF / usr/share/applications/xfce4-terminal-run.desktop

