#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
SOFTWARE_DIR="$SCRIPT_DIR"/../software
HYPR_CONFIG=$HOME/.config/hypr

cd $SCRIPT_DIR
$SCRIPT_DIR/syncfiles -e -r .

#echo "Special copy of thunar.xml"
#cat ~/.config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml | grep -E "xml|channel|hidden">$SCRIPT_DIR/.config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml

"$SOFTWARE_DIR"/ranger/update
"$SOFTWARE_DIR"/nvim/update
#"$SOFTWARE_DIR"/zathura/update
"$SOFTWARE_DIR"/tmux/update

