#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
SYNC_MODE=$1
REPO_DIR=$SCRIPT_DIR
SF="$SCRIPT_DIR/../bin/syncfiles $SYNC_MODE $REPO_DIR"


echo "Copying shell configs"
$SF ~ .bashrc
$SF ~ .bash_aliases
$SF ~ .zshrc
$SF ~ .p10k.zsh

echo "Copying X11 configs"
$SF ~ .xsession
$SF ~ .Xresources*

echo "Copying GTK configs"
$SF ~ .gtkrc-2.0
$SF ~ .config/gtk-3.0/settings.ini
$SF ~ .config/xsettingsd/xsettingsd.conf
$SF ~ .icons/default/index.theme
sudo $SF / usr/share/icons/default/index.theme
sudo $SF / etc/lightdm/slick-greeter.conf

echo "Copying picom config"
$SF ~ .config/picom.conf

echo "Copying xfce4 configs"
$SF ~ .config/xfce4/xfconf/xfce-perchannel-xml/xfce4-terminal.xml

echo "Copying .fehbg"
$SF ~ .fehbg

echo "Copying i3 config"
I3_CONFIG=".config/i3"
$SF ~ $I3_CONFIG/{config,workspaces.conf,i3blocks.conf}
$SF ~ $I3_CONFIG/scripts/.

echo "Copying dunst config"
$SF ~ .config/dunst/dunstrc

echo "Cpying libinput gestures"
$SF ~ .config/libinput-gestures.conf

echo "Copying mimeapps.list"
$SF ~ .config/mimeapps.list

