#!/bin/bash

# Experimental way to "link" files between the OS and the repo.

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

export SYNC_MODE=$1
export REPO_DIR=$SCRIPT_DIR


SF="$SCRIPT_DIR/../bin/syncfiles"



echo "Copying shell configs"
$SF ~ .bashrc
$SF ~ .bash_aliases
$SF ~ .zshrc
$SF ~ .p10k.zsh

echo "Copying X11 configs"
$SF ~ .xsession
$SF ~ .Xresources*

echo "Copying GTK configs"
$SF ~ .gtkrc-2.0
$SF ~ .config/gtk-3.0/settings.ini
$SF ~ .config/xsettingsd/xsettingsd.conf
$SF ~ .icons/default/index.theme
sudo $SF / usr/share/icons/default/index.theme
sudo $SF / etc/lightdm/slick-greeter.conf


#i3
I3_CONFIG=".config/i3"
$SF ~ $I3_CONFIG/{config,workspaces.conf,i3blocks.conf}
$SF ~ $I3_CONFIG/scripts/.



