#!/usr/bin/env bash

# Custom script for showing name of connected network
# and being able to open nm-connection-editor.

if [[ ! -z $BLOCK_BUTTON ]]; then
  nm-connection-editor &
fi

# Will be shown by the status bar
# Src endeavour i3
echo "$(LANG=C nmcli d | grep connected  | awk '{print $4}')"

