#!/bin/bash

# src: https://github.com/regolith-linux/remontoire
# If remontoire is running, kill it.  Otherwise start it.
remontoire_PID=$(pidof remontoire)

if [ -z "$remontoire_PID" ]; then
    # Remontoire is being funny, making it read from STDIN and specifying the config file is impossible
    cat ~/.config/i3/{workspaces.conf,theme-default-ish.conf,config} | remontoire -i
    # -c ~/.config/remontoire/remontoire.css
else
    kill $remontoire_PID
fi

