#!/bin/bash

MODE=$1
FILEPATH=$2

#xfce4-screenshooter --region --clipboard --save "$1"

if [[ "$MODE" == "region" ]]; then
    scrot --select "$FILEPATH"
elif [[ "$MODE" == "fullscreen" ]]; then
    scrot "$FILEPATH"
else
    echo "Must select mode"
    exit 1
fi

if [[ -f "$FILEPATH" ]]; then
    REPLY=$(notify-send --action "reply" "Screenshot saved to $FILEPATH")
    if [[ ! -z "$REPLY" ]]; then
        xdg-open "$FILEPATH"
    fi
fi

