#!/bin/bash
set -e

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

if [[ ! -z "remontoire" ]] && command -v "remontoire" 2>&1 >/dev/null; then
    if [[ ! $("$SCRIPT_DIR/../../bin/prompt-yn" "Do you wish to reinstall remontoire?") ]]; then
        exit 0
    fi
fi

REPO_DIR="$SCRIPT_DIR/remontoire-git"
"$SCRIPT_DIR"/../../bin/pkg-install vala
"$SCRIPT_DIR"/../../bin/pkg-install libgee
"$SCRIPT_DIR"/../../bin/pkg-install appstream-glib
"$SCRIPT_DIR"/../../bin/pkg-install meson
"$SCRIPT_DIR"/../../bin/pkg-install ninja

# src: https://github.com/regolith-linux/remontoire
echo "Building remontoire"
mkdir -p "$REPO_DIR"
cd "$REPO_DIR"
if [[ ! -d "$REPO_DIR/.git" ]]; then
    git clone https://github.com/regolith-linux/remontoire.git "$REPO_DIR"
#else
#    git reset --hard
fi
#git checkout 5bdde24df

#echo "Patching remontoire"
#git apply "$SCRIPT_DIR"/remontoire-patch.diff

if [[ -d "$REPO_DIR/build" ]]; then
    rm -rf "$REPO_DIR/build"
fi

meson build
cd build
ninja
ninja install

gsettings set org.regolith-linux.remontoire window-position "east"
gsettings set org.regolith-linux.remontoire window-padding-width 6
gsettings set org.regolith-linux.remontoire window-padding-height 6

echo "Remontoire build done!"

