#!/bin/bash


# Installing prerequisites
cwd=$(pwd)

# Install git
if ! command -v git 2>&1 >/dev/null
then
  echo "git not found, installing.."
  sudo pacman -Sy git
fi

# Install yay
if ! command -v yay 2>&1 >/dev/null
then
  echo "yay not found, installing.."
  sudo pacman -Sy --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
  # cleanup
  cd .. && rm -rf yay
fi

echo "Prerequisites installed."


# Install themes for awesomewm
mkdir -p ~/.config/awesome && cd ~/.config/awesome
if [ -f rc.lua ]
then
  echo "AwesomeWM config found, skipping.."
else
  echo "Setting up AwesomeWM.."
  git clone https://github.com/lcpz/awesome-copycats.git .
  git clone https://github.com/lcpz/awesome-freedesktop.git freedesktop
  git clone https://github.com/lcpz/lain.git lain
  echo "Copying rc.lua ."
  cp $(cwd)/rc.lua ~/.config/awesome/
  echo "AwesomeWM setup complete."
fi


# nvim-kickstart
mkdir -p ~/.config/nvim && cd ~/.config/nvim
if [ -f init.lua ]
then
  echo "nvim config found, skipping.."
else
  echo "Setting up nvim-kickstart.."
  git clone https://github.com/nvim-lua/kickstart.nvim.git .
  echo "Patching nvim-kickstart.."
  # patch created with git diff >filename.patch
  git apply $(cwd)/nvim-kickstart-patch.patch
  echo "nvim-kickstart setup complete."
fi


# alacritty
if [ -f ~/.config/alacritty/alacritty.toml ]
then
  echo "alacritty config found, skipping.."
else
  echo "Setting up Alacritty.."
  mkdir -p ~/.config/alacritty
  cp $(cwd)/alacritty.toml ~/.config/alacritty/
  echo "Alacritty setup complete."
fi


# oh my zsh
if [ -f ~/.oh-my-zsh/oh-my-zsh.sh ]
then
  echo "oh my zsh exists, skipping.."
else
  echo "Setting up oh my zsh .."
  sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
fi

if [ -d ~/.oh-my-zsh/plugins/zsh-syntax-highlighting ]
then
  echo "zsh-syntax-highlight -plugin found, skipping.."
else
  echo "Installing zsh-syntax-highlighting .."
  cd ~/.oh-my-zsh/plugins/
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
  echo "zsh-syntax-highlighting installed."
fi

if [ -d ~/.oh-my-zsh/plugins/zsh-autosuggestions ]
then
  echo "zsh-autosuggestions -plugin found, skipping.."
else
  echo "Installing zsh-autosuggestions .."
  cd ~/.oh-my-zsh/plugins/
  git clone https://github.com/zsh-users/zsh-autosuggestions
  echo "zsh-autosuggestions installed."
fi


# p10k theme
if [ -f ~/.p10k.zsh ]
then
  echo "p10k config found, skipping"
else
  echo "Installing powerlevel10k theme for zsh.."
  yay -S --noconfirm zsh-theme-powerlevel10k-git
  echo "powerlevel10k setup complete."
fi


echo "Copying .bashrc and .zshrc .."
cd $cwd
cp .bashrc ~/ && cp .zshrc ~/


