#!/bin/bash


# Installing prerequisites
cwd=$(pwd)

# Install git
if ! command -v git 2>&1 >/dev/null
then
  echo "git not found, installing.."
  sudo pacman -Sy git
fi

# Install yay
if ! command -v yay 2>&1 >/dev/null
then
  echo "yay not found, installing.."
  sudo pacman -Sy --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
  # cleanup
  cd .. && rm -rf yay
fi


# Install themes for awesomewm
mkdir -p ~/.config/awesome && cd ~/.config/awesome
if [ -f rc.lua ]
then
  echo "awesome config found, skipping.."
else
  git clone https://github.com/lcpz/awesome-copycats.git .
  git clone https://github.com/lcpz/awesome-freedesktop.git freedesktop
  git clone https://github.com/lcpz/lain.git lain
fi


# nvim-kickstart
mkdir -p ~/.config/nvim && cd ~/.config/nvim
if [ -f init.lua ]
then
  echo "nvim config found, skipping.."
else
  git clone https://github.com/nvim-lua/kickstart.nvim.git .
  # patch created with git diff >filename
  git apply $(cwd)/nvim-kickstart-patch.patch
fi


# zsh
# oh my zsh?
echo "copying .bashrc and .zshrc"
cp .bashrc ~/ && cp .zshrc ~/
yay -S --noconfirm zsh-theme-powerlevel10k-git


# alacritty
if [ -f ~/.config/alacritty/alacritty.toml ]
then
  echo "alacritty config found, skipping.."
else
  mkdir -p ~/.config/alacritty
  cp $(cwd)/alacritty.toml ~/.config/alacritty/
fi

