#!/bin/bash
set -e


CWD=$(pwd)

echo "Copying .bashrc"
cp ~/.bashrc "$CWD/"
echo "Copying .zshrc"
cp ~/.zshrc "$CWD/"
echo "Copying .xsession"
cp ~/.xsession "$CWD/"

echo "Copying rc.lua .."
cp ~/.config/awesome/rc.lua "$CWD/"

echo "Copying .p10k.zsh .."
cp ~/.p10k.zsh "$CWD/"

echo "Copying alacritty.toml"
cp ~/.config/alacritty/alacritty.toml "$CWD/"

echo "Copying ranger config"
cp ~/.config/ranger/rc.conf "$CWD/"


echo "Creating nvim-kickstart diff.."
cd ~/.config/nvim
git diff >"${CWD}/nvim-kickstart-patch.patch"

