#!/bin/bash
set -e


CWD=$(pwd)

cp2cwd() {
  cp $1 "$CWD/"
}

echo "Copying .bashrc"
cp2cwd ~/.bashrc
echo "Copying .zshrc"
cp2cwd ~/.zshrc
echo "Copying .xsession"
cp2cwd ~/.xsession
echo "Copying rc.lua .."
cp2cwd ~/.config/awesome/rc.lua
echo "Copying .p10k.zsh .."
cp2cwd ~/.p10k.zsh
echo "Copying alacritty.toml"
cp2cwd ~/.config/alacritty/alacritty.toml
echo "Copying ranger config"
cp2cwd ~/.config/ranger/rc.conf


echo "Creating nvim-kickstart diff.."
cd ~/.config/nvim
git diff >"${CWD}/nvim-kickstart-patch.patch"

