#!/bin/bash
set -e


SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
SOFTWARE_DIR="$SCRIPT_DIR"/../software

yoink() {
  cp $1 "$SCRIPT_DIR/"
}

echo "Copying .bashrc"
yoink ~/.bashrc
echo "Copying .zshrc"
yoink ~/.zshrc
echo "Copying .xsession"
yoink ~/.xsession
echo "Copying rc.lua .."
yoink ~/.config/awesome/rc.lua
echo "Copying .p10k.zsh .."
yoink ~/.p10k.zsh
echo "Copying alacritty.toml"
cp ~/.config/alacritty/alacritty.toml "$SOFTWARE_DIR"/alacritty/
echo "Copying ranger config"
cp ~/.config/ranger/rc.conf "$SOFTWARE_DIR"/ranger/


echo "Creating nvim-kickstart diff.."
cd ~/.config/nvim
git diff >"${SOFTWARE_DIR}/nvim/nvim-kickstart-patch.diff"

