#!/usr/bin/env bash

COMMAND="yay -Syu --noconfirm"

echo "Executing $COMMAND"
$COMMAND
echo "==========================================="
echo "Upgrade finished, you may close the window."
echo "==========================================="
exit 0

