#!/bin/bash

# original script: https://www.reddit.com/r/hyprland/comments/113ofeq/script_with_rofi_to_see_open_apps_and_switch_to/

hyprctl clients | \
	awk '/title:|workspace: ./ { gsub("\t*title: *", ""); gsub("\tworkspace: *", ""); gsub(" *\\([0-9]+\\)", ""); print }' | \
	paste -d "|" - - | \
	sort |\ # TODO: sort based on the actual workspace number instead of the characters
	tofi --prompt "Focus: " | \
	xargs -I{} hyprctl dispatch focuswindow "title:{}"

