#!/bin/bash

export SENSOR_CHIP=$GPU_TEMPERATURE_SENSOR
# set in the environment
#export GPU_BRAND=AMD
TEMPERATURE=$(~/.config/hypr/scripts/temperature | sed '2p;d')
USAGE=$(~/.config/i3/i3blocks-contrib/gpu-load/gpu-load | sed '2p;d')
if [[ -z "$TEMPERATURE" ]]; then TEMPERATURE="-"; fi
if [[ -z "$USAGE" ]]; then USAGE="-%"; fi
#VRAM=$(~/.config/hypr/scripts/memory)
# :w
echo "$TEMPERATURE| $USAGE"

