#!/usr/bin/env bash
# input src: EndeavourOS i3 dotfiles
# modified for this purpose


HYPR_SCRIPT_DIR="~/.config/hypr/scripts"

# menu defined as an associative array
typeset -A menu
# Could use grep -n ".*" for numbering but associative array doesn't
# retain order and I don't have the energy to fix this.
# Currently hard coding order with numbers and calling sort in the pipe
menu=(
  #[TODO]="hyprctl dispatch exec $HYPR_SCRIPT_DIR/dispatch-activeworkspace-clients settiled"
  # src: https://www.reddit.com/r/hyprland/comments/114rlm4/hyprctl_command_for_screen_rotation/
  # TODO select currently active display
  [r1 Rotate - Reset]="hyprctl keyword monitor $WM_DP1_NAME,$WM_DP1_RES,$WM_DP1_POS,$WM_DP1_SCALING"
  [r2 Rotate - Clockwise]="hyprctl keyword monitor $WM_DP1_NAME,$WM_DP1_RES,$WM_DP1_POS,$WM_DP1_SCALING,transform,3"
  [r3 Rotate - Counter clockwise]="hyprctl keyword monitor $WM_DP1_NAME,$WM_DP1_RES,$WM_DP1_POS,$WM_DP1_SCALING,transform,1"
  [r4 Rotate - Upside down]="hyprctl keyword monitor $WM_DP1_NAME,$WM_DP1_RES,$WM_DP1_POS,$WM_DP1_SCALING,transform,2"
)
menu_nrows=${#menu[@]}

launcher_exe="rofi"
launcher_options=(-dmenu -i -lines "${menu_nrows}")

launcher=(${launcher_exe} "${launcher_options[@]}")
selection="$(printf '%s\n' "${!menu[@]}" | sort | "${launcher[@]}")"
selection=${menu[${selection}]}

if [[ $? -eq 0 && ! -z ${selection} ]]; then
  $selection
fi

