#!/bin/bash

SCREENSHOT_DIR="$HOME/Screenshots"

MODE="$1"
FILEPATH="$2"
if [[ -z "$MODE" ]]; then
    MODE="region"
fi
if [[ -z "$FILEPATH" ]]; then
    mkdir -p "$SCREENSHOT_DIR"
    FILEPATH="$SCREENSHOT_DIR/$(date +"%Y-%m-%d-%T")-screenshot.png"
fi

if [[ "$MODE" == "region" ]]; then
    #scrot --select "$FILEPATH"
    grim -g "$(slurp)" $FILEPATH
elif [[ "$MODE" == "fullscreen" ]]; then
    #scrot "$FILEPATH"
    grim $FILEPATH
fi

if [[ -f "$FILEPATH" ]]; then
    REPLY=$(notify-send --action "reply" "Screenshot saved to $FILEPATH")
    if [[ ! -z "$REPLY" ]]; then
        feh -Z "$FILEPATH"
    fi
fi

